aws:
  access-key-id: YOUR_AWS_ACCESS_KEY_ID
  secret-access-key: YOUR_AWS_SECRET_ACCESS_KEY
  region: YOUR_AWS_REGION

dynamodb:
  mailbox-table: mailbox
  message-table: message

ses:
  region: YOUR_SES_REGION

cors:
  allowed-origins: "*"
  allowed-methods: GET, POST, DELETE
  allowed-headers: Content-Type, Authorization

spring:
  application:
    name: disposable-email-service
  data:
    dynamodb:
      endpoint: http://localhost:8000  # Change if using a different endpoint
  actuator:
    endpoints:
      web:
        exposure:
          include: "*"
